// This is loaded into the PhantomJs browser - do not edit - this is auto-generated by Gruntfile.js 
var __dirname = 'D:\Interview Tests\OrwellTest';
var __dirnameglobal = 'D:\Interview Tests\OrwellTest';